#! /bin/sh

# ----- Daemons ----- #

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
pgrep -x picom > /dev/null || picom --no-frame-pacing --config $HOME/.config/picom/picom.conf &
pgrep -x dunst > /dev/null || dunst &
pgrep -x udiskie > /dev/null || udiskie &

# ----- Visuals ----- #

# Disable screen sleep
xset -dpms
xset s off

# Screen refresh rate
xrandr --dpi 96 --refresh 60 &

# Border
bspc config border_width              2

# Window gaps
bspc config window_gap                6

# Monocle mode settings
bspc config single_monocle            true
bspc config gapless_monocle           true
bspc config borderless_monocle        true

# Default cursor
xsetroot -cursor_name left_ptr

# Split ratio
bspc config split_ratio               1

# Desktop names
bspc monitor -d 1 2 3 4 5

# Focusing
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config focused_border_color "#a9b1d6"
bspc config normal_border_color "#32344a"

# Other
bspc config pointer_motion_interval   7
bspc config pointer_follows_monitor   true
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

# ----- Functionality ----- #

# Make the key repeat faster
xset r rate 300 50 &

# Turkish QWERTY keyboard layout
setxkbmap tr
